### ISSUE TITLE
gwizard-example is out of sync with release versions

### ISSUE THREAD

**Issue by heuermh** [gwizard/gwizard-example#1]
Appears that gwizard-example isn't kept in sync with release versions in https://github.com/stickfigure/gwizard repo; i.e. pom.xml

``` xml
<gwizard.version>0.2-SNAPSHOT</gwizard.version>
```

should probably be release version 0.3 and 

``` xml
<version>1.0-SNAPSHOT</version>
```

could be 0.4-SNAPSHOT.

**Comment by stickfigure** [comment]
Good catch. I changed gwizard.version to 0.3. I don't see much point in updating the pom <version> for the example app since there will never be a real release of it, though.

Thanks!

**Comment by heuermh** [comment]
Great, thank you!
